### PR TITLE
Guide tabs

### PR DESCRIPTION
**Pull request by orladoylenvs**
@danielinteractive here's what I meant about using .panel-tabsets and removing the R code to create customs ones. 

Not ready to merge - I need to double check I didn't mess up any of the links.

### CODE REVIEW

**Comment by danielinteractive** [comment]
Thanks @orladoylenvs , nice work. 

Here my suggestion is to save some manual copy/pasting for newly introduced tabsets by compressing for example

```
::: {.panel-tabset}

## <img src="https://www.r-project.org/logo/Rlogo.svg" alt="alt text" width="25">

[roxygen2](https://roxygen2.r-lib.org/)

## <img src="https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg" alt="alt text" width="25">

[docstrings](https://peps.python.org/pep-0257/)

## <img src="https://raw.githubusercontent.com/JuliaLang/julia-logo-graphics/master/images/julia-dots.svg" width="25">

[docstrings](https://docs.julialang.org/en/v1/manual/documentation/)
:::
```

into something like

```r
 guide_tabset(
    r = guide_tab("roxygen2", "https://roxygen2.r-lib.org/"),
    python = guide_tab("docstrings", "https://peps.python.org/pep-0257/"),
    julia = guide_tab("docstrings", "https://docs.julialang.org/en/v1/manual/documentation/")
)
```

inside a `{r results="asis", echo=FALSE}` block, thereby also decoupling the formatting and the code.

**Comment by orladoylenvs** [comment]
Do you think it's worth developing custom code given the copying and pasting is a one-off and we can use the panel-tabset formatting quite simply?

**Comment by danielinteractive** [comment]
Yes, I think it is worth :-) (similarly as I have done before, does not take much time and keeps the content lean and clean)

**Comment by danielinteractive** [comment]
@orladoylenvs should I give it a try and commit on this branch? just in case you are busy

**Comment by orladoylenvs** [comment]
That would be great!

**Review by danielinteractive — APPROVED** [review]
@orladoylenvs if it looks good to you then you can merge

**Comment by orladoylenvs** [comment]
Thanks @danielinteractive!

**Pull request merged**
